name: Build and Deploy Sphinx Documentation

# Execute this workflow automatically when we push to muster
on:
  push:
    branches: [main]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade sphinx
          pip install --upgrade sphinx-rtd-theme
          
        # pip install --upgrade nbsphinx          
        # pip install --upgrade pandoc
        # nbsphinx is needed to convert jupyter notebooks to html
        # pandoc is needed to convert markdown to html

        # python -m pip install -U sphinx
        # python -m pip install sphinx-rtd-theme

      - name: Build Documentation
        run: |
          make clean
          make html

      #- name: Deploy to GitHub Pages
      #  uses: peaceiris/actions-gh-pages@v3
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    publish_dir: build/html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the folder with manually generated html
          path: 'build/html'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
